language: java
jdk:
- oraclejdk8
os:
- linux
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: lambda
  function_name: mentalArithmetic
  region: us-east-1
  role: arn:aws:iam::578713470651:role/dotzi_aws_lambda
  runtime: java8
  module_name: "de.dotzinerd.mentalarithmetic"
  handler_name: "MentalArithmeticStreamHandler"
  file: "mentalArithmetic-0.0.1-SNAPSHOT-jar-with-dependencies.jar"
env:
  global:
  - secure: O5OznLQ/zKA9PyD8nfW//arMCQL1tu3bcLXfQUaUxeDp1eJqoqVyDpuEgfQX5UmPNm90W8K6kv73IP8cZ3N/71aJX9WQx/kswjWA8OUlImB3djYsAq+lBCHxm7QM71eLwCDwJ/WbI85Fw3Y3pdSi9ZsrLmuxzYwYzSjl8WU+uXBlGneV31AU5zXbCWYDFLVVj8q/N50naj1Z1+yZTXzoNwQ9tphLQhZBmL1lCC0l0PpXdeQiCqxtHllAzAnYdZjCDjrW6tTYzI96zLui9j1+etQBRe6Ij5KgLdKOV1LX/EgwYtI9voJyQwMNyVHPcqWjOqH0VJ/SfeTQQSl5J+15S1ACy1vfmrSzHdMMNU96eWLZvy6Nf3lfq4MIVzAZ/Fq1IFKL+zJaFjF1PeSY79Ob5e3Sdj7EJm8PZLSJ5OVODKbwN1eognwCFV1mkASeI5iXNKGrETYjQDDaP4sPS/fhM6nCduMpDg8ojVJRH4dcZ+39usMFx+Xrm5ekcUGIhdkUmrd3Jh2rLT0s0Gc5MkJoDw1/NcQ3ZiKHRSG99DUU0FO1bN7ImIFzUmzFsKnmOI1xrtVuyDajZMVp7YekA3eNbYkzMRSA5SiHJ7iLPuY7Rbba/h4tUA7kT756vwm4DM+uTfEyWxxBNEzwsz6r3uxeJRkPROUs6LOT/vHJzvfYlSk=
  - secure: Qg901i7tNxioQrOEO7WMLZiann59HwLYGgwon3RBx/9houe+2U9wI85FYgD5YerDZpvLZecafmBZ4PP6qBfnd1+EfSEDyxbuKck5tKqSIxCv/+/D4XwxinPDtrn8VqhIG3RxQ75oJ2ucNVOuGcj/fnOjGkz7lMhzHqMMgBpvpYEaEaTSg8SHPtfuJoeEEdQsuXETNmCkoWO1Fj0g9N11WTgLQLoWFq0DyHcn0D5rmMlxlrhA0lUyKLBPTW/pzUm6b5tnKGb1LoGPv41eN1+8haQxr9lmxxGY8VaGPb+9+mHm5o3oVDukezr1fBLoZs9IprKRQ8C1NrQpDqK3OGQC26o7ymsVtQ4c4MRAIoyKUu3IP3MLYXb7lAFMKr5BJ2P23vB800Zp6X0pX6ZibkUVGnZvQssV4ohcChCs5SF8K+9EeLRNi0aHc8QZepQdNAS1AmzWEL4Bg69sVAiGFTTrniwr4F27r4bDNc2WdWAZdeJu2I5fWfySzVeIBgcbG2HUn3qycgd/X3ULktQ7fNvgtplNC3JPmKLcW/4RdfqWTgdlGIPkX3U8U8k2chntcZoNgbUmtdgLNU5740ayM5obcS1EXAlbLSYIyb9lVxpdvMFja7DolIsHlWIpoxy2iPuNvfLS+ndrct17HgS/sEivjnyNsxoEWR3smPQFi7tfitQ=
script: mvn assembly:assembly -DdescriptorId=jar-with-dependencies package