language: java
jdk:
- oraclejdk8
os:
- linux
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: lambda
  function_name: mentalArithmetic
  region: us-east-1
  role: arn:aws:iam::578713470651:role/dotzi_aws_lambda
  runtime: java8
  handler_name: de.dotzinerd.mentalarithmetic.MentalArithmeticStreamHandler
  access_key_id: AKIAIOUK3MTMHVNSZJYA
  secret_access_key:
    secure: RJYXQyC5QF2yk5Nid1TzurSV9PNPwKhCNcwMtjnqX48F/2DF5qMXLPP3TclGkOgteVSLjWxTr/KECd5BQms5tOi6eA9cjPVhDN9P8R8uVlG1O1/ZVP/Pjw6giUaFEBbkdWvoHRa0QGi7jJNF9rgEeed3HlmHm2j1gpVY7+SZf44OxYbq3MdODz//mstRcPRb2SQv0rVBP2oE8DAzFIcjEurKIy3SRobkappAFpawq9x1M3ycDv5TCFbvq4niv32auA0IBZ/bLY+/on33EnGvquQs9EzO4PhGNpo3120rw2ORpwGD9wj8oSDHc83CPMOrxQIRzd+xoSdW3ouJGOWT73shtCWF3E/Z0hkviUCqSAMRzgeGXPKmeFSs2/Z/ydjFu+Ykr6YR77EjDG42t9Q7Zyh0Fx28k+HztwcpLtCFntiBfTeyP9833YaQAS6iA+vuJicF4QBM4FnZ3d24X9IcJ1flWKbezFaNDVSFw5Na4pCo1i2o8LMdx5WCYCoEpnoVBLVALYv0PK9zhdBhi0x5Q4KZ7BU3rkhSUTC6pPWIXCz5E6KYZEJ7Z8h8xkWhyDW13ffU0l3iPlkJ8YLDR4cxOWoCLq/BpsZ2RdZGbFizwIN9OzWQ7b7pvNO2dwm1sDwn+0UbhvyeUPih8qjPtiGE0008kHHJzDFO/y+9/n2XGZU=
