language: java
jdk:
- oraclejdk8
os:
- linux
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: lambda
  function_name: mentalArithmetic
  region: us-east-1
  role: arn:aws:iam::578713470651:role/dotzi_aws_lambda
  runtime: java8
  handler_name: de.dotzinerd.mentalarithmetic.MentalArithmeticStreamHandler
env:
  global:
  - secure: mvLoj4IIqKe4LvUA3Y1z+quz5oeiqd4ZhMODyAJtROUnE2Uu3UaRGmxWwqcGUTWkIqCBwyO4da1kcjbHJqrQobuPYzjYxWWZXwvQ34gm1ZNldSxielO+2lEHuX85RjDzlsOzw/Sbpz1b7THJwMXX6TTYZgu9dWdNuRN2gsI8r/tDIT15wqtMEOnDJ/nVoC+5C8z2f1yazB+Y1mVH1krX6/MXwScq0kFVNSj4VXKLQX6JWcidb+Hz9uAa0gy48WkLmNjDEzUJE9RlzjhuRCJycYV0Xtff9KdGEI0BoYvqpk7mutMUfiypuSq4YKPgEjHv6d9b3kucAjB7Ps61BzakgAyxgVuMdK+1uFUI7+lcU58QYGqDVKh+59ZZSrtKZ8uHpiCztF/FpcWSGx12iAdsjg/PdYLhiEIHRHyLDeMUKWZeAOusMxZ7zKS7nAq62SKnw4a06iMpZs5eeSKVXLWWlV4p7tjBIvyVBclqReVW97XCz9r2Q6uscQq5S2pD24z/a7n9iwUB9pVU7ozt4QXBfYJe5StYcuUWYcwtTezx+Casbj7Td4VO7eQoJdUbv3dgbtcCPaA2LJihdoC8cVlx5pIclQPKM0H9dOHfDlWKvOdAspqXPgeheq25ZdNahIOEzqU/KfgHkXk2aSVdqehWRI774G9fye6gJ9N1D/HqhyY=
  - secure: qElGc53I0l6mMfN+QeGBEsQ0yeMVt1F19Z+GIK3+0Ivkpq9oYSJfnRQVV4zRFIvlXm8XmQnK8oAJkjrlaDWb572GHeq2AOUyJzkP0MKRYlHFdvL9UWIIvyHCZEBCefYLeJ4fmDUfs3S6Mg3krwCZvQprK8SBlr0nzlgQ/n4vKpIEQa+xNa/x9cXaftGt6er4YFdss1C+ZRoP220DjZcQd4EnxOarO492lTtRLGhVzmH3Jv/TeZU+Mesx7sdsmwda95Q5U5z1puXm1vykoCA+R8DmUXoPoK1ccTVd6xyt7Y+DwLDNNDu4ZH1ahzhPFKMqN9Qsqv0PxcJzMxiBp7l7c9ST/9ZivIxQeGagK/63UkISMhffwcL+BrRpFuS83ClqIy6edC0SiPxZDCkwPJYFdmS4LqBf2dXetR1KtpD/+9vIxrXzLjticNCAaC17EAMpQFU3oFAXetUfbU5sHkuEGd9FYBxc8SSNLoJhUgliEplT7vIpn8cO7Bs2g8XaZ3+pWdxsH6Wxwu99WnQY4RN+yryZUlxozLXUNuuFZ+RGcnzDgPOgZs/yvD7E1K8e4p+g+/xNIF100z9Wtp9O+Oa60WFEs1UwksPoCFFrSXYXoO9xIubI0tNm+rkBuwIQ6iY9GQMI7Xsz/U4YBz2TWr6ichiVugYzWvNtD7zMpxcupYM=
